name: Build and Deploy CV

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    uses: tobiaslocker/docframe/build-workflow.yml@main
    with:
      md_file: cv.md
      metadata_file: metadata.yaml
      output_name: cv

